name: Release on Push
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Create Release and Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v0.${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false
      # - name: Create Tag
      #   if: success()
      #   uses: mathieudutour/github-tag-action@v5
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     tag: v0.${{ github.run_number }}
      #     message: 'New release: v0.${{ github.run_number }}'
